# Generated by Django 4.1.6 on 2023-02-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('subtotal', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Страна')),
                ('tax_rate', models.IntegerField(verbose_name='Размер налога')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_group', models.CharField(max_length=20, verbose_name='Статус покупателя')),
                ('discount', models.IntegerField(verbose_name='Размер скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=20, verbose_name='Валюта')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('stock_amount', models.IntegerField(default=0, verbose_name='Количество на складе')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total', models.IntegerField(verbose_name='Общая стоимость')),
                ('total_with_tax_and_sale', models.IntegerField(verbose_name='Итого')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='Адрес доставки')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart', verbose_name='Список товаров')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discount', verbose_name='Персональная скидка')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
